package joselobo_lab6p2;

import java.util.ArrayList;
import javax.swing.RepaintManager;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author rinal
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_CrearUsuario = new javax.swing.JFrame();
        lb_TituloCrearUsuario = new javax.swing.JLabel();
        lb_UserName = new javax.swing.JLabel();
        tb_Username = new javax.swing.JTextField();
        lb_PasswordCreate = new javax.swing.JLabel();
        tb_PasswordCreate = new javax.swing.JTextField();
        lb_Edad = new javax.swing.JLabel();
        js_Edad = new javax.swing.JSpinner();
        B_CrearUsuario = new javax.swing.JButton();
        jP_CrearArtista = new javax.swing.JPanel();
        lb_NombreDeArtista = new javax.swing.JLabel();
        B_CrearArtista = new javax.swing.JButton();
        tb_NombreDeArtista = new javax.swing.JTextField();
        lb_TipoDeCuenta = new javax.swing.JLabel();
        jC_TipodeCuenta = new javax.swing.JComboBox<>();
        B_ReturnaCrear_Inicio = new javax.swing.JButton();
        jF_Usuario = new javax.swing.JFrame();
        jT_Usuario = new javax.swing.JTabbedPane();
        jP_Usuario_Main = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree_Usuarios = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        JList_Favoritas = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jF_Artista = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTree_Artista = new javax.swing.JTree();
        jPanel4 = new javax.swing.JPanel();
        P_CantAlbun = new javax.swing.JPanel();
        lb_AlbunName = new javax.swing.JLabel();
        tf_NombreAlbun = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JS_CantAlbun = new javax.swing.JSpinner();
        B_AlbunCrear = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        B_CrearAlbun = new javax.swing.JButton();
        B_CrearSingle = new javax.swing.JButton();
        P_CrearAlbun = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_TituloCancionAlbun = new javax.swing.JTextField();
        tf_DuracionCancionAlbun = new javax.swing.JTextField();
        B_SiguienteCancionAlbun = new javax.swing.JButton();
        lb_TituloLogin = new javax.swing.JLabel();
        tb_Usuario = new javax.swing.JTextField();
        lb_Usuario = new javax.swing.JLabel();
        lb_Password = new javax.swing.JLabel();
        tb_Password = new javax.swing.JPasswordField();
        B_IniciarSeccion = new javax.swing.JButton();
        B_CrearUsuarioLogin = new javax.swing.JButton();

        jf_CrearUsuario.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jf_CrearUsuario.setTitle("Crear Usuario");

        lb_TituloCrearUsuario.setText("Crear Usuario");

        lb_UserName.setText("UserName");

        lb_PasswordCreate.setText("Password");

        lb_Edad.setText("Edad");

        B_CrearUsuario.setLabel("Crear Usuario");
        B_CrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_CrearUsuarioMouseClicked(evt);
            }
        });

        lb_NombreDeArtista.setText("Nombre de Artista");

        B_CrearArtista.setText("Crear Artista");
        B_CrearArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_CrearArtistaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jP_CrearArtistaLayout = new javax.swing.GroupLayout(jP_CrearArtista);
        jP_CrearArtista.setLayout(jP_CrearArtistaLayout);
        jP_CrearArtistaLayout.setHorizontalGroup(
            jP_CrearArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_CrearArtistaLayout.createSequentialGroup()
                .addGroup(jP_CrearArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_CrearArtistaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jP_CrearArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_CrearArtista)
                            .addComponent(lb_NombreDeArtista)))
                    .addGroup(jP_CrearArtistaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(tb_NombreDeArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jP_CrearArtistaLayout.setVerticalGroup(
            jP_CrearArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_CrearArtistaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lb_NombreDeArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tb_NombreDeArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(B_CrearArtista)
                .addGap(22, 22, 22))
        );

        lb_TipoDeCuenta.setText("Tipo de Cuenta");

        jC_TipodeCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Artista" }));
        jC_TipodeCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_TipodeCuentaActionPerformed(evt);
            }
        });

        B_ReturnaCrear_Inicio.setText("Return");
        B_ReturnaCrear_Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_ReturnaCrear_InicioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_CrearUsuarioLayout = new javax.swing.GroupLayout(jf_CrearUsuario.getContentPane());
        jf_CrearUsuario.getContentPane().setLayout(jf_CrearUsuarioLayout);
        jf_CrearUsuarioLayout.setHorizontalGroup(
            jf_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_CrearUsuarioLayout.createSequentialGroup()
                .addGroup(jf_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_CrearUsuarioLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(lb_TituloCrearUsuario))
                    .addGroup(jf_CrearUsuarioLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jf_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_UserName)
                            .addGroup(jf_CrearUsuarioLayout.createSequentialGroup()
                                .addGroup(jf_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tb_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_PasswordCreate)
                                    .addComponent(tb_PasswordCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_Edad)
                                    .addComponent(lb_TipoDeCuenta)
                                    .addComponent(jC_TipodeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_CrearUsuario)
                                    .addComponent(js_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jf_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jf_CrearUsuarioLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                        .addComponent(jP_CrearArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jf_CrearUsuarioLayout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(B_ReturnaCrear_Inicio)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(194, 194, 194))
        );
        jf_CrearUsuarioLayout.setVerticalGroup(
            jf_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_CrearUsuarioLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lb_TituloCrearUsuario)
                .addGap(18, 18, 18)
                .addComponent(lb_UserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jf_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jf_CrearUsuarioLayout.createSequentialGroup()
                        .addComponent(tb_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_PasswordCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_PasswordCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_Edad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(js_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jP_CrearArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_TipoDeCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jC_TipodeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jf_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_CrearUsuario)
                    .addComponent(B_ReturnaCrear_Inicio))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jP_Usuario_Main.setName("Main"); // NOI18N

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Listas");
        jTree_Usuarios.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree_Usuarios);

        JList_Favoritas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "a" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(JList_Favoritas);

        javax.swing.GroupLayout jP_Usuario_MainLayout = new javax.swing.GroupLayout(jP_Usuario_Main);
        jP_Usuario_Main.setLayout(jP_Usuario_MainLayout);
        jP_Usuario_MainLayout.setHorizontalGroup(
            jP_Usuario_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_Usuario_MainLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jP_Usuario_MainLayout.setVerticalGroup(
            jP_Usuario_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_Usuario_MainLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jP_Usuario_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jT_Usuario.addTab("Main", jP_Usuario_Main);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        jT_Usuario.addTab("Otras Listas", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        jT_Usuario.addTab("Listas", jPanel3);

        javax.swing.GroupLayout jF_UsuarioLayout = new javax.swing.GroupLayout(jF_Usuario.getContentPane());
        jF_Usuario.getContentPane().setLayout(jF_UsuarioLayout);
        jF_UsuarioLayout.setHorizontalGroup(
            jF_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jT_Usuario)
        );
        jF_UsuarioLayout.setVerticalGroup(
            jF_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jT_Usuario)
        );

        jF_Artista.setPreferredSize(new java.awt.Dimension(800, 500));

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Albunes");
        JTree_Artista.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(JTree_Artista);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(550, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Main", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_AlbunName.setText("Nombre del Albun");

        jLabel1.setText("Cantidad de Canciones A crear");

        B_AlbunCrear.setText("Crear");
        B_AlbunCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_AlbunCrearMouseClicked(evt);
            }
        });

        jLabel2.setText("Dia de Lanzamiento");

        javax.swing.GroupLayout P_CantAlbunLayout = new javax.swing.GroupLayout(P_CantAlbun);
        P_CantAlbun.setLayout(P_CantAlbunLayout);
        P_CantAlbunLayout.setHorizontalGroup(
            P_CantAlbunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_CantAlbunLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(P_CantAlbunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B_AlbunCrear)
                    .addGroup(P_CantAlbunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JS_CantAlbun, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_NombreAlbun, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_AlbunName)
                        .addComponent(jLabel1)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        P_CantAlbunLayout.setVerticalGroup(
            P_CantAlbunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_CantAlbunLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(lb_AlbunName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_NombreAlbun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JS_CantAlbun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B_AlbunCrear)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jPanel4.add(P_CantAlbun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 450));

        B_CrearAlbun.setText("Crear Albun");
        B_CrearAlbun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_CrearAlbunMouseClicked(evt);
            }
        });
        jPanel4.add(B_CrearAlbun, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        B_CrearSingle.setText("Crear Single");
        B_CrearSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CrearSingleActionPerformed(evt);
            }
        });
        jPanel4.add(B_CrearSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel3.setText("Titulo");

        jLabel4.setText("Duracion");

        B_SiguienteCancionAlbun.setText("Siguiente");
        B_SiguienteCancionAlbun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_SiguienteCancionAlbunMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout P_CrearAlbunLayout = new javax.swing.GroupLayout(P_CrearAlbun);
        P_CrearAlbun.setLayout(P_CrearAlbunLayout);
        P_CrearAlbunLayout.setHorizontalGroup(
            P_CrearAlbunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_CrearAlbunLayout.createSequentialGroup()
                .addGroup(P_CrearAlbunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_CrearAlbunLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(P_CrearAlbunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(tf_TituloCancionAlbun)
                            .addComponent(tf_DuracionCancionAlbun, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)))
                    .addGroup(P_CrearAlbunLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(B_SiguienteCancionAlbun)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        P_CrearAlbunLayout.setVerticalGroup(
            P_CrearAlbunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_CrearAlbunLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_TituloCancionAlbun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_DuracionCancionAlbun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(B_SiguienteCancionAlbun)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jPanel4.add(P_CrearAlbun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 450));

        jTabbedPane1.addTab("Crear", jPanel4);

        javax.swing.GroupLayout jF_ArtistaLayout = new javax.swing.GroupLayout(jF_Artista.getContentPane());
        jF_Artista.getContentPane().setLayout(jF_ArtistaLayout);
        jF_ArtistaLayout.setHorizontalGroup(
            jF_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jF_ArtistaLayout.setVerticalGroup(
            jF_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        lb_TituloLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_TituloLogin.setText("Login");

        lb_Usuario.setText("User");

        lb_Password.setText("Password");

        B_IniciarSeccion.setText("Iniciar Seccion");
        B_IniciarSeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_IniciarSeccionMouseClicked(evt);
            }
        });

        B_CrearUsuarioLogin.setText("Crear Usuario");
        B_CrearUsuarioLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_CrearUsuarioLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_Usuario)
                            .addComponent(tb_Usuario)
                            .addComponent(lb_Password)
                            .addComponent(tb_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(lb_TituloLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(B_IniciarSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_CrearUsuarioLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lb_TituloLogin)
                .addGap(18, 18, 18)
                .addComponent(lb_Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lb_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(B_IniciarSeccion)
                .addGap(34, 34, 34)
                .addComponent(B_CrearUsuarioLogin)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_CrearUsuarioLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CrearUsuarioLoginMouseClicked
        // TODO add your handling code here:
        jf_CrearUsuario.pack();
        this.setVisible(false);
        jf_CrearUsuario.setLocationRelativeTo(this);
        jf_CrearUsuario.setVisible(true);

        jP_CrearArtista.setVisible(false);
    }//GEN-LAST:event_B_CrearUsuarioLoginMouseClicked

    private void B_ReturnaCrear_InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_ReturnaCrear_InicioMouseClicked
        // TODO add your handling code here:
        this.setVisible(true);
        jf_CrearUsuario.setVisible(false);
    }//GEN-LAST:event_B_ReturnaCrear_InicioMouseClicked

    private void jC_TipodeCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_TipodeCuentaActionPerformed
        // TODO add your handling code here:
        if (jC_TipodeCuenta.getSelectedIndex() == 1) {
            B_CrearUsuario.setVisible(false);
            jP_CrearArtista.setVisible(true);
        } else {
            B_CrearUsuario.setVisible(true);
            jP_CrearArtista.setVisible(false);
        }
    }//GEN-LAST:event_jC_TipodeCuentaActionPerformed

    private void B_CrearArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CrearArtistaMouseClicked
        // TODO add your handling code here:
        boolean test = true;
        for (int i = 0; i < usuarios.size(); i++) {

            if (tb_Username.getText().equals(usuarios.get(i).getUsername())) {
                test = false;
                break;
            }
        }
        if ((int) js_Edad.getValue() >= 18) {
            if (test) {
                Artista A = new Artista(tb_NombreDeArtista.getText(), tb_Username.getText(), tb_PasswordCreate.getText(), (int) js_Edad.getValue());
                usuarios.add(A);
                JOptionPane.showMessageDialog(this, "Usuario Creado", "Usuario Creado", 1);

            } else {
                JOptionPane.showMessageDialog(this, "Nombre de usuario ya existe", "Usuario Invalido", 2);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tiene que ser mayor de 18 anos", "Menor de Edad", 2);

        }
    }//GEN-LAST:event_B_CrearArtistaMouseClicked

    private void B_CrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CrearUsuarioMouseClicked
        // TODO add your handling code here:

        boolean test = true;
        for (int i = 0; i < usuarios.size(); i++) {
            if (tb_Username.getText().equals(usuarios.get(i).getUsername())) {
                test = false;
                break;
            }
        }
        if ((int) js_Edad.getValue() >= 12) {
            if (test) {
                Cliente C = new Cliente(tb_Username.getText(), tb_PasswordCreate.getText(), (int) js_Edad.getValue());
                usuarios.add(C);
                tb_Username.setText("");
                tb_PasswordCreate.setText("");
                JOptionPane.showMessageDialog(this, "Usuario Creado", "Usuario Creado", 1);

            } else {
                JOptionPane.showMessageDialog(this, "Nombre de usuario ya existe", "Usuario Invalido", 2);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tiene que ser mayor de 12 anos", "Menor de Edad", 2);
        }
    }//GEN-LAST:event_B_CrearUsuarioMouseClicked

    private void B_IniciarSeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_IniciarSeccionMouseClicked
        // TODO add your handling code here:
        int ubicacion = -1;
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getUsername().equals(tb_Usuario.getText())) {
                ubicacion = i;
            }
        }
        if (ubicacion != -1) {
            if (usuarios.get(ubicacion).getContrasena().equals(tb_Password.getText())) {
                UsuarioActual = usuarios.get(ubicacion);
                if (usuarios.get(ubicacion) instanceof Artista) {
                    jF_Artista.pack();
                    jF_Artista.setLocationRelativeTo(this);
                    jF_Artista.setVisible(true);
                    DefaultTreeModel T = (DefaultTreeModel) JTree_Artista.getModel();
                    DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) T.getRoot();
                    for (Albun n : ((Artista) UsuarioActual).getAlbunes()) {
                        DefaultMutableTreeNode r = new DefaultMutableTreeNode(n);
                        raiz.add(r);
                        for (Cancion m : n.getCanciones()) {
                            DefaultMutableTreeNode s = new DefaultMutableTreeNode(m);
                            r.add(s);
                        }
                    }
                } else {
                    jF_Usuario.pack();
                    jF_Usuario.setLocationRelativeTo(this);
                    jF_Usuario.setVisible(true);
                    DefaultTreeModel T = (DefaultTreeModel) jTree_Usuarios.getModel();
                    DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) T.getRoot();
                    for (Reproduccion reproduccion : ((Cliente) UsuarioActual).getReproducciones()) {
                        DefaultMutableTreeNode r = new DefaultMutableTreeNode(reproduccion);
                        raiz.add(r);
                    }
                    for (int i = 0; i < raiz.getChildCount(); i++) {
                        DefaultMutableTreeNode R = (DefaultMutableTreeNode) raiz.getChildAt(i);
                        ArrayList<Cancion> a = ((Reproduccion) R.getUserObject()).getCanciones();
                        for (Cancion cancion : a) {
                            DefaultMutableTreeNode r = new DefaultMutableTreeNode(a);
                            ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(r);
                        }
                    }
                    T.reload();
                    P_CantAlbun.setVisible(false);
                    P_CrearAlbun.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Contrase\u00f1a Incorrecta", "Contrase\u00f1a Incorrecta", 2);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El Usuario no existe", "Error de Usuario", 2);
        }

    }//GEN-LAST:event_B_IniciarSeccionMouseClicked

    private void B_CrearAlbunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CrearAlbunMouseClicked
        // TODO add your handling code here:
        P_CantAlbun.setVisible(true);
    }//GEN-LAST:event_B_CrearAlbunMouseClicked

    private void B_AlbunCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_AlbunCrearMouseClicked
        // TODO add your handling code here:
        A = new Albun(listaDeLanzamiento.size() + 1, 0, jDateChooser1.getDate().toString(), tf_NombreAlbun.getText());
        P_CantAlbun.setVisible(false);
        P_CrearAlbun.setVisible(true);
        cont = 0;
    }//GEN-LAST:event_B_AlbunCrearMouseClicked

    private void B_SiguienteCancionAlbunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_SiguienteCancionAlbunMouseClicked
        // TODO add your handling code here:
        if (cont < ((int) JS_CantAlbun.getValue())) {
            A.AddCanciones(new Cancion(tf_TituloCancionAlbun.getText(), tf_DuracionCancionAlbun.getText(), listaDeLanzamiento.size() + 1));
            cont++;
        } else {
            P_CrearAlbun.setVisible(false);
            ((Artista) UsuarioActual).getAlbunes().add(A);
        }
        tf_TituloCancionAlbun.setText("");
        tf_DuracionCancionAlbun.setText("");
    }//GEN-LAST:event_B_SiguienteCancionAlbunMouseClicked

    private void B_CrearSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CrearSingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_CrearSingleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_AlbunCrear;
    private javax.swing.JButton B_CrearAlbun;
    private javax.swing.JButton B_CrearArtista;
    private javax.swing.JButton B_CrearSingle;
    private javax.swing.JButton B_CrearUsuario;
    private javax.swing.JButton B_CrearUsuarioLogin;
    private javax.swing.JButton B_IniciarSeccion;
    private javax.swing.JButton B_ReturnaCrear_Inicio;
    private javax.swing.JButton B_SiguienteCancionAlbun;
    private javax.swing.JList<String> JList_Favoritas;
    private javax.swing.JSpinner JS_CantAlbun;
    private javax.swing.JTree JTree_Artista;
    private javax.swing.JPanel P_CantAlbun;
    private javax.swing.JPanel P_CrearAlbun;
    private javax.swing.JComboBox<String> jC_TipodeCuenta;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFrame jF_Artista;
    private javax.swing.JFrame jF_Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jP_CrearArtista;
    private javax.swing.JPanel jP_Usuario_Main;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jT_Usuario;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTree jTree_Usuarios;
    private javax.swing.JFrame jf_CrearUsuario;
    private javax.swing.JSpinner js_Edad;
    private javax.swing.JLabel lb_AlbunName;
    private javax.swing.JLabel lb_Edad;
    private javax.swing.JLabel lb_NombreDeArtista;
    private javax.swing.JLabel lb_Password;
    private javax.swing.JLabel lb_PasswordCreate;
    private javax.swing.JLabel lb_TipoDeCuenta;
    private javax.swing.JLabel lb_TituloCrearUsuario;
    private javax.swing.JLabel lb_TituloLogin;
    private javax.swing.JLabel lb_UserName;
    private javax.swing.JLabel lb_Usuario;
    private javax.swing.JTextField tb_NombreDeArtista;
    private javax.swing.JPasswordField tb_Password;
    private javax.swing.JTextField tb_PasswordCreate;
    private javax.swing.JTextField tb_Username;
    private javax.swing.JTextField tb_Usuario;
    private javax.swing.JTextField tf_DuracionCancionAlbun;
    private javax.swing.JTextField tf_NombreAlbun;
    private javax.swing.JTextField tf_TituloCancionAlbun;
    // End of variables declaration//GEN-END:variables
//Mis Variables
    ArrayList<Usuario> usuarios = new ArrayList();
    ArrayList<Reproduccion> listasDeReproduccion = new ArrayList();
    ArrayList<Lanzamiento> listaDeLanzamiento = new ArrayList();
    ArrayList<Cancion> canciones = new ArrayList();
    Usuario UsuarioActual;
    Albun A;
    int cont;

}
